name: car_maintenance_system_new
description: A comprehensive car maintenance management system with Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  
  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Date & Time
  intl: ^0.20.2
  
  # Charts
  fl_chart: ^0.66.0
  
  # Responsive UI
  flutter_screenutil: ^5.9.3
  
  # Rating Bar
  flutter_rating_bar: ^4.0.1

  # Notifications
  flutter_local_notifications: ^17.0.0
  
  # Image Picker
  image_picker: ^1.0.7
  
  # Database
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # URL Launcher
  url_launcher: ^6.2.2
  
  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  
  # PDF Generation
  pdf: ^3.10.8
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true